[package]
name = "dune"
version = "0.1.0"
authors = ["adam-mcdaniel <adam.mcdanie17@gmail.com>"]
edition = "2018"

[[bin]]
name = "dune"
path = "src/bin.rs"

[dependencies]
honeycomb = "0.1.4"
xmachine = "0.1.11"
read_input = "0.8"
dirs = "2.0"